using AutoMapper;
using Domain.Contracts;
using Domain.Exceptions;
using Domain.Models;
using Microsoft.Extensions.Logging;
using Services.Abstractions;
using Services.Abstractions.DTOs.Assessment;
using System.Text.Json;

namespace Services;

public class AssessmentService : IAssessmentService
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IAiServiceClient _aiServiceClient;
    private readonly IMapper _mapper;
    private readonly ILogger<AssessmentService> _logger;

    public AssessmentService(
        IUnitOfWork unitOfWork,
        IAiServiceClient aiServiceClient,
        IMapper mapper,
        ILogger<AssessmentService> logger)
    {
        _unitOfWork = unitOfWork;
        _aiServiceClient = aiServiceClient;
        _mapper = mapper;
        _logger = logger;
    }

    public async Task<AssessmentDto> CreateAssessmentAsync(CreateAssessmentDto request, string userId)
    {
        var jobPost = await _unitOfWork.JobPosts.GetByIdAsync(request.JobPostId);
        if (jobPost == null)
            throw new NotFoundException($"Job post {request.JobPostId} not found");

        var assessment = _mapper.Map<Assessment>(request);
        assessment.TotalScore = assessment.Questions.Sum(q => q.Points);
        
        _unitOfWork.Assessments.Create(assessment);
        await _unitOfWork.SaveChangesAsync();
        
        return _mapper.Map<AssessmentDto>(assessment);
    }

    public async Task<AssessmentDto> GenerateAiAssessmentAsync(int jobPostId, int questionCount, string userId)
    {
        var jobPost = await _unitOfWork.JobPosts.GetByIdAsync(jobPostId);
        if (jobPost == null)
            throw new NotFoundException($"Job post {jobPostId} not found");

        var questionsText = await _aiServiceClient.GenerateAssessmentAsync(jobPost.Description, questionCount);
        
        var assessment = new Assessment
        {
            JobPostId = jobPostId,
            Title = $"AI Generated Assessment for {jobPost.Title}",
            Description = "Automatically generated by AI based on job requirements.",
            Type = Domain.Enums.AssessmentType.Technical,
            TimeLimitMinutes = questionCount * 2, // 2 mins per question
            IsAiGenerated = true,
            IsActive = true
        };

        int order = 1;
        foreach (var qText in questionsText)
        {
            assessment.Questions.Add(new Question
            {
                Text = qText,
                Type = Domain.Enums.QuestionType.OpenEnded, // Default for AI gen for now
                Points = 10,
                OrderIndex = order++
            });
        }
        
        assessment.TotalScore = assessment.Questions.Sum(q => q.Points);

        _unitOfWork.Assessments.Create(assessment);
        await _unitOfWork.SaveChangesAsync();

        return _mapper.Map<AssessmentDto>(assessment);
    }

    public async Task<AssessmentDto> GetAssessmentAsync(int assessmentId)
    {
        var assessment = await _unitOfWork.Assessments.GetWithQuestionsAsync(assessmentId);
        if (assessment == null)
            throw new NotFoundException($"Assessment {assessmentId} not found");

        return _mapper.Map<AssessmentDto>(assessment);
    }

    public async Task<IEnumerable<AssessmentDto>> GetAssessmentsForJobAsync(int jobPostId)
    {
        var assessments = await _unitOfWork.Assessments.GetByJobPostAsync(jobPostId);
        return _mapper.Map<IEnumerable<AssessmentDto>>(assessments);
    }

    public async Task<CandidateAssessmentDto> StartAssessmentAsync(int assessmentId, int jobApplicationId, string candidateId)
    {
        var assessment = await _unitOfWork.Assessments.GetWithQuestionsAsync(assessmentId);
        if (assessment == null)
            throw new NotFoundException($"Assessment {assessmentId} not found");

        // Check if already started
        var existing = await _unitOfWork.CandidateAssessments.GetByCandidateAndAssessmentAsync(candidateId, assessmentId);
        if (existing != null)
        {
            if (existing.IsCompleted)
                throw new BadRequestException("Assessment already completed");
                
            return _mapper.Map<CandidateAssessmentDto>(existing);
        }

        var candidateAssessment = new CandidateAssessment
        {
            CandidateId = candidateId,
            AssessmentId = assessmentId,
            JobApplicationId = jobApplicationId,
            StartedAt = DateTime.UtcNow,
            IsCompleted = false
        };

        _unitOfWork.CandidateAssessments.Create(candidateAssessment);
        await _unitOfWork.SaveChangesAsync();

        return _mapper.Map<CandidateAssessmentDto>(candidateAssessment);
    }

    public async Task<CandidateAssessmentDto> SubmitAssessmentAsync(SubmitAssessmentDto request, string candidateId)
    {
        var attempt = await _unitOfWork.CandidateAssessments.GetByCandidateAndAssessmentAsync(candidateId, request.AssessmentId);
        
        if (attempt == null)
            throw new NotFoundException("Assessment attempt not found. Please start the assessment first.");
            
        if (attempt.IsCompleted)
            throw new BadRequestException("Assessment is already submitted.");

        var assessment = await _unitOfWork.Assessments.GetWithQuestionsAsync(request.AssessmentId);
        
        // Time limit check (with 1 minute grace period)
        if (attempt.StartedAt.HasValue && assessment != null)
        {
            var allowedEndTime = attempt.StartedAt.Value.AddMinutes(assessment.TimeLimitMinutes + 1);
            if (DateTime.UtcNow > allowedEndTime)
            {
                attempt.IsCompleted = true;
                attempt.SubmittedAt = DateTime.UtcNow;
                attempt.Score = 0; // Penalty for overtime
                attempt.Answers = request.Answers;
                
                _unitOfWork.CandidateAssessments.Update(attempt);
                await _unitOfWork.SaveChangesAsync();
                
                throw new BadRequestException("Assessment time limit exceeded.");
            }
        }

        attempt.Answers = request.Answers;
        attempt.SubmittedAt = DateTime.UtcNow;
        attempt.IsCompleted = true;
        
        // Simple auto-grade logic for demonstration (assuming JSON answers)
        // In reality, we would parse JSON answers and compare with CorrectAnswer
        attempt.Score = 0; // Needs grading logic for real deployment

        _unitOfWork.CandidateAssessments.Update(attempt);
        await _unitOfWork.SaveChangesAsync();

        return _mapper.Map<CandidateAssessmentDto>(attempt);
    }

    public async Task<CandidateAssessmentDto> GetCandidateAssessmentAsync(int assessmentId, string candidateId)
    {
        var attempt = await _unitOfWork.CandidateAssessments.GetByCandidateAndAssessmentAsync(candidateId, assessmentId);
        if (attempt == null)
            throw new NotFoundException("Assessment attempt not found.");

        return _mapper.Map<CandidateAssessmentDto>(attempt);
    }

    public async Task<IEnumerable<CandidateAssessmentDto>> GetCandidateAssessmentsAsync(string candidateId)
    {
        var attempts = await _unitOfWork.CandidateAssessments.GetByCandidateAsync(candidateId);
        return _mapper.Map<IEnumerable<CandidateAssessmentDto>>(attempts);
    }
}
